include:
  - remote: 'https://gitlab.com/mediacodex/infrastructure/-/raw/master/gitlab/sonarcloud.yml'
  - remote: 'https://gitlab.com/mediacodex/infrastructure/-/raw/master/gitlab/terraform.yml'

default:
  image: node:erbium
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - node_modules/

stages:
  - install
  - validate
  - plan
  - build
  - deploy

install:
  stage: install
  script: 
    - npm ci

lint:
  stage: validate
  script:
    - npm run lint

build:
  stage: build
  script:
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist/

.deploy:
  stage: deploy
  image:
    name: amazon/aws-cli
  script:
    - aws s3 cp dist s3://$BUCKET --recursive

deploy_dev:
  extends:
    - .deploy
  environment:
    name: development
  variables:
    BUCKET: mediacodex-dev-website
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID_dev
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY_dev
  dependencies:
    - build
  only:
    - master

deploy_prod:
  extends:
    - .deploy
  environment:
    name: production
  variables:
    BUCKET: mediacodex-prod-website
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID_prod
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY_prod
  dependencies:
    - build
  only:
    - master
  when: manual
