include:
  - remote: 'https://gitlab.com/mediacodex/infrastructure/-/raw/master/gitlab/sonarcloud.yml'

default:
  image: node:erbium

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

stages:
  - install
  - lint

install:
  stage: install
  script: 
    - npm ci

lint:
  stage: lint
  script:
    - npm run lint