include:
  - remote: 'https://gitlab.com/mediacodex/infrastructure/-/raw/master/gitlab/sonarcloud.yml'
  - remote: 'https://gitlab.com/mediacodex/infrastructure/-/raw/master/gitlab/terraform.yml'

default:
  image: node:erbium
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - node_modules/

stages:
  - install
  - validate
  - plan
  - build
  - deploy

install:
  stage: install
  script: 
    - npm ci

lint:
  stage: validate
  script:
    - npm run lint

build:
  stage: build
  script:
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist/

.deploy:
  stage: deploy
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  script:
    - terraform init
    - terraform workspace new $CI_ENVIRONMENT_NAME
    - terraform apply -auto-approve

deploy_dev:
  extends:
    - .deploy
  environment:
    name: development
  dependencies:
    - build
  only:
    - master

deploy_prod:
  extends:
    - .deploy
  environment:
    name: production
  dependencies:
    - build
  only:
    - master
  when: manual
